name: CI
on:
  push:
  release:
    types:
      - created

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node-${{ runner.os }}-
      - run: npm ci
      - name: Test
        run: |
          npm run pretest
      - name: Check VS Code engine version
        run: |
          ok=$(jq '.engines.vscode == .devDependencies["@types/vscode"]' package.json)
          if [  "${ok}" != 'true' ]; then
            echo "Mismatch between VS Code engine version and @types/vscode version"
            echo "Please update engine version in package.json"
            exit 1
          fi

  release:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'release'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node-${{ runner.os }}-
      - run: npm ci
      - name: Release (Visual Studio Marketplace)
        run: |
          npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
      - name: Release (Open VSX)
        run: |
          npm run deploy-ovsx
        env:
          OVSX_TOKEN: ${{ secrets.OVSX_TOKEN }}
